name: Build Twrp 11

on:
  workflow_dispatch:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@main

      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email "yilliee@protonmail.com"
          git config --global user.name "Yillié"

      - uses: rokibhasansagar/slimhub_actions@main
      - run: printenv | sort

      - name: Establish the build environment
        run: |
          cp -r $PWD ~/device-tree
          sudo apt update -y
          sudo apt upgrade -y
          sudo DEBIAN_FRONTEND=noninteractive apt-get install \
          openjdk-8-jdk android-tools-adb bc bison \
          build-essential curl flex g++-multilib gcc-multilib \
          gnupg gperf imagemagick lib32ncurses5-dev \
          lib32readline-dev lib32z1-dev liblz4-tool \
          libncurses5-dev libsdl1.2-dev libssl-dev \
          libxml2 libxml2-utils lzop \
          pngcrush rsync schedtool squashfs-tools xsltproc \
          yasm zip zlib1g-dev python bison build-essential \
          curl flex git gnupg gperf ccache \
          liblz4-tool libncurses5-dev libsdl1.2-dev \
          libxml2 libxml2-utils lzop pngcrush \
          schedtool squashfs-tools xsltproc zip zlib1g-dev \
          build-essential kernel-package libncurses5-dev bzip2 \
          python wget gcc g++ curl sudo libssl-dev openssl -y
          export JACK_SERVER_VM_ARGUMENTS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx3g"
          sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
          sudo chmod a+rx /usr/local/bin/repo

      - name: Sync twrp-11 source
        run: |
          mkdir ~/twrp-11
          cd ~/twrp-11
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11 --depth=1
          repo sync --force-sync
          repo sync --force-sync

      - name: Copy the device tree
        run: |
          mkdir -p ~/twrp-11/device/samsung
          cp -r ~/device-tree ~/twrp-11/device/samsung/exynos9611
          rm ~/twrp-11/device/samsung/exynos9611/vendorsetup.sh

      - name: Build recoveryimage
        run: |
          cd ~/twrp-11 && export ALLOW_MISSING_DEPENDENCIES=true && . build/envsetup.sh && lunch twrp_exynos9611-eng && mka recoveryimage

      - name: Upload recovery image
        run: |
          cd ~/twrp-11/out/target/product/exynos9611
          curl -sL https://git.io/file-transfer | sh
          ./transfer wet recovery.img

